### ISSUE TITLE
This Integrator is not bound to a context!

### ISSUE THREAD

**Issue by francoviscarra** [essex-lab/grand#16]
Hello,

I'm trying to run GCNCMC but I get the following error:

```
Traceback (most recent call last):
  File "/biggin/b196/scro4068/GCNCMC/run_gcncmc.py", line 82, in <module>
    gcncmc_mover.move(simulation.context, 1)
  File "/biggin/b196/scro4068/miniconda3/lib/python3.10/site-packages/grand/samplers.py", line 1307, in move
    self.insertionMove()
  File "/biggin/b196/scro4068/miniconda3/lib/python3.10/site-packages/grand/samplers.py", line 1335, in insertionMove
    self.ncmc_integrator.step(self.n_prop_steps_per_pert)
  File "/biggin/b196/scro4068/miniconda3/lib/python3.10/site-packages/openmm/openmm.py", line 18830, in step
    return _openmm.CustomIntegrator_step(self, steps)
openmm.OpenMMException: This Integrator is not bound to a context!
```
My script is based on one of the examples from the paper:

```python
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *
from openmmtools.integrators import BAOABIntegrator
from sys import stdout
import numpy as np
import mdtraj
import argparse
import grand
from openmmforcefields.generators import GAFFTemplateGenerator
from openff.toolkit.topology import Molecule
from openmmforcefields.generators import SystemGenerator
from parmed.gromacs import GromacsTopologyFile
import parmed

parser = argparse.ArgumentParser()
parser.add_argument('--pert', type=int, default=99, help='Number of perturbation steps per NCMC move')
parser.add_argument('--prop', type=int, default=50, help='Number of propagation steps between each perturbation')
args = parser.parse_args()

pdb = PDBFile('minim.pdb')
                                

# Add ghost waters
pdb.topology, pdb.positions, ghosts = grand.utils.add_ghosts(pdb.topology, pdb.positions,
                                                             n=15, pdb='prod-ghosts.pdb')

# Create system
forcefield = ForceField('amber14-all.xml','amber14/protein.ff14SB.xml', 'amber14/tip3p.xml', 'NS.xml')



system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, 
                                 nonbondedCutoff=12*angstrom,
                                 switchDistance=10*angstrom, 
                                 constraints=HBonds)

# Define reference atoms for the GCMC sphere
ref_atoms = [{'name': 'CA', 'resname': 'TRP', 'resid': '156', 'chain': 0},
             {'name': 'CA', 'resname': 'GLU', 'resid': '198', 'chain': 0}]



# Define integrator
integrator = BAOABIntegrator(310*kelvin, 1.0/picosecond, 0.002*picosecond)


# Define platform and precision
platform = Platform.getPlatformByName('CUDA')
platform.setPropertyDefaultValue('Precision', 'mixed')


# Create GCMC sampler object
gcncmc_mover = grand.samplers.NonequilibriumGCMCSphereSampler(system=system, 
                                                              topology=pdb.topology, 
                                                              temperature=310*kelvin, 
                                                              integrator=integrator,
                                                              nPertSteps=args.pert,
                                                              nPropStepsPerPert=args.prop,
                                                              referenceAtoms=ref_atoms, 
                                                              sphereRadius=6*angstroms, 
                                                              ghostFile="prod-ghosts.txt", 
                                                              log="prod.log", 
                                                              rst="prod.rst7", 
                                                              dcd="prod.dcd", 
                                                              overwrite=True)



# Create simulation object and set positions, velocities and box vectors
simulation = Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(310*kelvin)
simulation.context.setPeriodicBoxVectors(*pdb.topology.getPeriodicBoxVectors())

# Initialise the GCMC mover
gcncmc_mover.initialise(simulation.context, ghosts)

# Run GCNCMC/MD production - 4000 iterations of 1 NCMC move and 5 ps MD
for i in range(4000):
    simulation.step(2500)
    gcncmc_mover.move(simulation.context, 1)
    gcncmc_mover.report(simulation)

```

I have no idea what may be causing this, it is worth noting that my system was prepared in GROMACS and I converted the ligand topology using `grand.utils` `create_ligand_xml` and  `write_conect` (as my ligand topology was originally generated using antechamber).

**Comment by olliemelling** [comment]
Hi,

When you define your simulation object, you need to make sure the integrator is the same one that is being used in the gcncmc_mover object. So it needs to be:

`simulation = Simulation(pdb.topology, system, gcncmc_mover.compound_integrator, platform)`

This should work - please let me know if not

Thanks,

Ollie

**Comment by francoviscarra** [comment]
Many thanks Ollie, it works now.
